# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/divider/divider.xci
# IP: The module: 'divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/divider/src/mult_32_20_lm/mult_32_20_lm.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: d:/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/divider/divider.xci
# IP: The module: 'divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/divider/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet
