# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/mult_pos/mult_pos.xci
# IP: The module: 'mult_pos' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/mult_pos/mult_pos_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_pos'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/mult_pos/mult_pos.xci
# IP: The module: 'mult_pos' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/hdmi_vga_zybo/hdmi_vga_zybo.srcs/sources_1/ip/mult_pos/mult_pos_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_pos'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
